### ISSUE TITLE
Something is wrong here.

### ISSUE THREAD

**Issue by aryank2240** [ashish-jha-2004/CP_Problem_Solved#1]
Sir, from when did you started doing this many problems.  I am a great fan of yours. Can you teach me how to code. I will be grateful to you if you could give me any advice.

Btw you can make your repo private if you just want to use GitHub as a code dump.

**Comment by ashish-jha-2004** [comment]
Hey! Thanks a lot for your kind words—it means a lot to hear that my work has been helpful to you. 😊

I started doing competitive programming regularly a couple of years back, focusing on understanding problem-solving techniques and improving step-by-step. My advice to you would be:

    Master the Basics: Ensure you're comfortable with data structures like arrays, linked lists, stacks, and essential algorithms like sorting and searching.

    Practice Consistently: CP is all about regular practice. Start with problems that match your level, and gradually tackle more difficult ones. Revisit easier problems occasionally to solidify your understanding.

    Learn to Debug Efficiently: Getting good at debugging can save a lot of time and frustration. Practice writing clean, modular code that’s easy to debug and test.

    Understand Time Complexity: This is crucial for efficient problem-solving and will help you choose the right approach, especially as problems get more complex.

    Use Resources: Platforms like Codeforces, LeetCode, and AtCoder offer a good variety of problems. Analyze editorials after attempting problems to learn new techniques.

    Participate in Contests: Regular participation in online contests helps build speed and accuracy under time pressure.

As for making the repo private, that’s a good idea if I decide to use it purely for personal use. For now, I'm happy to keep it public as it seems helpful to others like you. :)

I hope this helps, and feel free to reach out if you have any questions. Happy coding, and good luck with your CP journey! 🚀

**Comment by aryank2240** [comment]
What should I study if I want to make a client to server authentication system.

**Comment by ashish-jha-73** [comment]
Hmm, Itna din ke baad yaad kiya woh bhi stalk karke ??

**Comment by aryank2240** [comment]
bro it's not stalking. I randomly stumbled upon your LinkedIn which brought me up here.
